version: "3"
services:
  app:
    build:
      context: .
      args:
        VITE_SUPABASE_URL: http://supabase:8000
        VITE_SUPABASE_KEY: examplekey
    ports:
      - "80:80"
    depends_on:
      - supabase
  supabase:
    image: supabase/supabase-dev:latest
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_SCHEMA: public
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    command:
      - postgres
      - "-c"
      - wal_level=logical
volumes:
  db-data:
